### ISSUE TITLE
Code review feb 5

### ISSUE THREAD

**Issue by mumbleskates** [T4Man/portfolio#4]
Looks pretty good! The only thing I noticed that looks a little odd is: When the page is viewed on a narrow screen (in the mobile layout) and the menu is popped down by hovering on the menu icon, the image in the background of the header bar moves downwards as the `site-header` element expands. Trying to make it so the image does not appear to jump around would be an interesting thing to work on; I'm not sure exactly how best to do that, myself.

Code nitpicks:

**projects.js:**
`ProjectData` is capitalized; this is generally reserved for class names. This should be changed to `projectData`, both here and where it is referenced in main.js line 25.

**about.js:**
Same as above: `AboutData` should probably not be capitalized (also in main.js line 21).

**main.js:**
Some extra whitespace at the end of the file; usually you want to end the file with a single newline, but extra blank lines may end up cluttering up over time.

On lines 11 and 16, you are compiling the templates anew every time they are used. These templates can be defined at the top of the file, perhaps as `aboutTemplate` and `projectTemplate`, only compiled once (which is comparatively slow), and used as functions from there on.

Lines 37 through 47 are indented but not in side another block.

**base.css:**
They've been recommending we add a `body { max-width: 100%; }` declaration for our base layouts (line 1 comment)

Lines 12, 21, and 36: Be sure to include consistent whitespace between blocks!

**layout.css:**
There is a missing `}` for the media query block at the end of the file.

Likewise, put some blank line whitespace between your blocks here so the file matches the style of your base.css file.

**modules.css:**
In the .tab class declaration on line 97, there are border widths defined for top, left, and right but not bottom. Is this intentional? If so it would be clearer to write `border-width: 1px 1px 0 1px;`, and if you wish all the sides to be the same this can be `border-width: 1px;`.

**Comment by T4Man** [comment]
Excellent feedback that helped me clean up my code structure. I had several 'sleepy' mistakes.
